pipeline {
    agent none
    stages {
        // stage('Git Clone') { 
        //         steps {
        //             git branch: 'master', url: 'https://github.com/Mirfani340/simple-python-pyinstaller-app'
        //         }
        //     }
        stage('Build') {
            agent {
                docker {
                    image 'frolvlad/alpine-python3'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deploy') {
            agent {
                docker {
                    image 'six8/pyinstaller-alpine'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}